- name: variables info
  hosts: local
  connection: local
  vars_files:
    course.yaml
  tasks:
    - name: printing variables 
      ansible.builtin.debug:
        msg: "Hi Welcome to {{ INSTITUTE }}, we will {{ COURSE }}, within {{ DURATION }}"
