- name: playbook1
  hosts: frontend
  become: true
  tasks:
    - name: Installing nginx using dnf
      ansible.builtin.dnf:
        name: nginx
        state: present
      when:
        ansible_os_family == "RedHat"
        

    - name: Installing nginx using apt
      ansible.builtin.apt:
        name: nginx
        state: present
      when:
        ansible_os_family == "debian"
        

      