- name: installing packages
  hosts: frontend
  become: yes
  tasks:
    - name: installing packages
      ansible.builtin.packages:
       name: "{{ item }}"
       state: present
      loop:
      - nginx
      - Git 
      - zip